version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp_container
    ports:
      - "443:443"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=myflaskapp

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myflaskapp
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql  # Añade un volumen para persistir los datos de MySQL
    ports:
      - "3307:3306"

volumes:
  mysql_data:  # Define un volumen persistente para MySQL
